# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10-jessie

    working_directory: ~/repo

    steps:
    - checkout

    - restore_cache:
        name: Restore Yarn package cache
        keys:
        - v2-dependencies-{{ checksum "yarn.lock" }}
        # fallback to using the latest cache if no exact match is found
        - v2-dependencies-

    - run:
        name: Install dependencies
        command: yarn install

    - save_cache:
        name: Save Yarn package cache
        key: v2-dependencies-{{ checksum "yarn.lock" }}
        paths:
        - ~/.cache/yarn

    - run:
        name: Build the project
        command: yarn build

    - run:
        name: Run tests
        command: yarn test --ci

    - store_artifacts:
        name: Store test results
        path: target/test-results
        prefix: test-results

    - store_artifacts:
        name: Store coverage reports
        path: target/coverage
        prefix: coverage

    - store_test_results:
        name: Upload test results # to display in Test Summary
        path: target/test-results

    - run:
        name: Upload code coverage report
        command: yarn codecov --disable=gcov

    - run:
        name: Linting
        command: yarn lint
