import { AfterEvent } from '../after-event';
import { AfterEvent__symbol, EventKeeper, EventSupplier, isEventKeeper } from '../base';
import { afterSent } from './after-sent';

/**
 * Builds an {@link AfterEvent} keeper of events sent by the given `keeper`.
 *
 * @category Core
 * @typeParam TEvent - An event type. This is a list of event receiver parameter types.
 * @param keeper - A keeper of events.
 *
 * @returns An {@link AfterEvent} keeper of events originated from the given `keeper`.
 */
export function afterSupplied<TEvent extends any[]>(
  keeper: EventKeeper<TEvent>,
): AfterEvent<TEvent>;

/**
 * Builds an {@link AfterEvent} keeper of events sent by the given `supplier`.
 *
 * The event generated by `fallback` will be sent to the registered first receiver, unless `supplier` sends one.
 *
 * This is a synonym of {@link afterSent}, unless `supplier` is an {@link EventKeeper}.
 *
 * @typeParam TEvent - An event type. This is a list of event receiver parameter types.
 * @param supplier - An event supplier.
 * @param fallback - A function creating fallback event. When omitted, the initial event is expected to be sent by
 * `supplier`. A receiver registration would lead to an error otherwise.
 *
 * @returns An {@link AfterEvent} keeper of events either originated from the given `supplier`, or `initial` one.
 */
export function afterSupplied<TEvent extends any[]>(
  supplier: EventSupplier<TEvent>,
  fallback?: (this: void) => TEvent,
): AfterEvent<TEvent>;

export function afterSupplied<TEvent extends any[]>(
  supplier: EventSupplier<TEvent>,
  fallback?: (this: void) => TEvent,
): AfterEvent<TEvent> {
  return isEventKeeper(supplier) ? supplier[AfterEvent__symbol]() : afterSent(supplier, fallback);
}
